[package]
name = "domani"
version = "0.0.0"
authors = ["konojunya <junya03dance@gmail.com>"]
edition = "2018"
repository = "https://github.com/konojunya/domani"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"
image = "0.10.0"
reqwest = "0.9.17"